### ISSUE TITLE
Citation of the Original Paper

### ISSUE THREAD

**Issue by LinguList** [lexibank/pharaocoracholaztecan#1]
So far,  have:

> Pharao Hansen, Magnus (2020): ¿Familia o vecinos? Investigando la relación entre el proto-náhuatl y el proto-corachol [Family or neighbors? Investigating the relation between Proto-Náhuatl and Proto-Corachol].

But I need the volume and editors, etc. Ideally also in BibTeX format.

**Comment by Maunus** [comment]
The book is "Lenguas yutoaztecas: historia, estructuras y contacto lingüístico. Homenaje a Karen Dakin". Rosa Yañez (ed.) Guadalajara: Universidad de Guadalajara.

**Comment by Maunus** [comment]
title=¿Familia o vecinos? Investigando la relación entre el proto-náhuatl y el proto-corachol [Family or neighbors? Investigating the relation between Proto-Náhuatl and Proto-Corachol].
chapter=3
author=Pharao Hansen, Magnus
year=2020
booktitle=Lenguas yutoaztecas: historia, estructuras y contacto lingüístico. Homenaje a Karen Dakin
editor=Yañez Rosales, Rosa H.
publisher=Universidad de Guadalajara
isbn=978-607-547-808-1

**Comment by LinguList** [comment]
Nice, we add this later.

**Comment by Maunus** [comment]
I am guessing there is going to be a DOI, but there isn't one yet.
