### ISSUE TITLE
Check prosody/phonotactics

### ISSUE THREAD

**Issue by chrzyki** [lexibank/pharaocoracholaztecan#13]
|   Type | ID                               | Value                                        | Form          | Graphemes               | Segments        |
|-------:|:---------------------------------|:---------------------------------------------|:--------------|:------------------------|:----------------|
|      1 | ProtoNahua-28-blood-1            | *yes <**pauso                                | yes <pauso    | ^ ye s + <pauso $       | j e s +         |
|      1 | ProtoNahua-39-ear-1              | *nakas <*nakasV                              | nakas <nakasV | ^ n a k a s + <nakasV $ | n a k a s +     |
|      1 | ProtoNahua-46-foot-1             | *ikši <**kèsi/kàsi                           | ikši <kèsi    | ^ i k š i + <kèsi $     | i k ʃ i +       |
|      1 | ProtoUtoAztecan-11-heavy-1       | *pɨttɨ PUA                                   | pɨttɨ PUA     | ^ p ɨ tt ɨ + PUA $      | p ɨ t t ɨ +     |
|      1 | ProtoUtoAztecan-12-dry-1         | *waki PUA                                    | waki PUA      | ^ w a k i + PUA $       | w a k i +       |
|      1 | ProtoUtoAztecan-13-colditscold-1 | *sep- PUA                                    | sep- PUA      | ^ s e p - + PUA $       | s e p + +       |
|      1 | ProtoUtoAztecan-15-woman-1       | **sinwa PUA/**uka- PUA                       | sinwa PUA     | ^ s i n w a + PUA $     | s i n w a +     |
|      1 | ProtoUtoAztecan-15-woman-2       | **sinwa PUA/**uka- PUA                       | uka- PUA      | ^ u k a - + PUA $       | u k a + +       |
|      1 | ProtoUtoAztecan-17-person-2      | **ta:wi/*tɨwi PUA                            | tɨwi PUA      | ^ t ɨ w i + PUA $       | t ɨ w i +       |
|      1 | ProtoUtoAztecan-18-fish-1        | **musi SUA/**ki¢u PUA                        | musi SUA      | ^ m u s i + SUA $       | m u s i +       |
|      1 | ProtoUtoAztecan-18-fish-2        | **musi SUA/**ki¢u PUA                        | ki¢u PUA      | ^ k i ¢ u + PUA $       | k i ts u +      |
|      1 | ProtoUtoAztecan-19-bird-1        | *wi¢iki PUA                                  | wi¢iki PUA    | ^ w i ¢ i k i + PUA $   | w i ts i k i +  |
|      1 | ProtoUtoAztecan-20-dog-1         | **¢u SUA                                     | ¢u SUA        | ^ ¢ u + SUA $           | ts u +          |
|      1 | ProtoUtoAztecan-21-louse-1       | **atɨ PUA                                    | atɨ PUA       | ^ a t ɨ + PUA $         | a t ɨ +         |
|      1 | ProtoUtoAztecan-22-snake-1       | **kowa PUA                                   | kowa PUA      | ^ k o w a + PUA $       | k o w a +       |
|      1 | ProtoUtoAztecan-23-tree-1        | **kua-wi SUA                                 | kua-wi SUA    | ^ k ua - w i + SUA $    | k u a + w i +   |
|      1 | ProtoUtoAztecan-25-leef-1        | **sàmwá SUA                                  | sàmwá SUA     | ^ s à mw á + SUA $      | s a mʷ a +      |
|      1 | ProtoUtoAztecan-26-root-1        | **nawa SUA                                   | nawa SUA      | ^ n a w a + SUA $       | n a w a +       |
|      1 | ProtoUtoAztecan-27-seed-1        | **pa¢i PUA/**wa¢I SUA                        | pa¢i PUA      | ^ p a ¢ i + PUA $       | p a ts i +      |
|      1 | ProtoUtoAztecan-27-seed-2        | **pa¢i PUA/**wa¢I SUA                        | wa¢I SUA      | ^ w a ¢ I + SUA $       | w a ts i +      |
|      1 | ProtoUtoAztecan-28-blood-1       | **pau PUA/                                   | pau PUA       | ^ p au + PUA $          | p a u +         |
|      1 | ProtoUtoAztecan-31-bone-1        | **ohomɨ PUA                                  | ohomɨ PUA     | ^ o h o m ɨ + PUA $     | o h o m ɨ +     |
|      1 | ProtoUtoAztecan-32-grease-1      | **wip PUA                                    | wip PUA       | ^ w i p + PUA $         | w i p +         |
|      1 | ProtoUtoAztecan-35-tail-1        | **kwasi PUA                                  | kwasi PUA     | ^ kw a s i + PUA $      | kʷ a s i +      |
|      1 | ProtoUtoAztecan-36-feather-1     | **ana PUA/**piwi PUA/**kɨ¢a PUA              | ana PUA       | ^ a n a + PUA $         | a n a +         |
|      1 | ProtoUtoAztecan-36-feather-2     | **ana PUA/**piwi PUA/**kɨ¢a PUA              | piwi PUA      | ^ p i w i + PUA $       | p i w i +       |
|      1 | ProtoUtoAztecan-36-feather-3     | **ana PUA/**piwi PUA/**kɨ¢a PUA              | kɨ¢a PUA      | ^ k ɨ ¢ a + PUA $       | k ɨ ts a +      |
|      1 | ProtoUtoAztecan-37-hair-1        | **¢omi PUA/**kuppa PUA                       | ¢omi PUA      | ^ ¢ o m i + PUA $       | ts o m i +      |
|      1 | ProtoUtoAztecan-37-hair-2        | **¢omi PUA/**kuppa PUA                       | kuppa PUA     | ^ kuppa + PUA $         | k u pp a +      |
|      1 | ProtoUtoAztecan-38-head-1        | **muu PUA/*kuppa                             | muu PUA       | ^ m uu + PUA $          | m uː +          |
|      1 | ProtoUtoAztecan-39-ear-1         | **nakka PUA                                  | nakka PUA     | ^ n a kk a + PUA $      | n a k k a +     |
|      1 | ProtoUtoAztecan-4-two-1          | *wo- SUA/(*wapulai ‘different/other’ cahita) | wo- SUA       | ^ w o - + SUA $         | w o + +         |
|      1 | ProtoUtoAztecan-41-nose-1        | **yeka SUA/**¢o ‘snout’ SUA                  | yeka SUA      | ^ ye k a + SUA $        | j e k a +       |
|      1 | ProtoUtoAztecan-43-tooth-1       | **tame SUA                                   | tame SUA      | ^ t a m e + SUA $       | t a m e +       |
|      1 | ProtoUtoAztecan-44-tongue-1      | *nenɨ SUA                                    | nenɨ SUA      | ^ n e n ɨ + SUA $       | n e n ɨ +       |
|      1 | ProtoUtoAztecan-47-knee-1        | **taŋa PUA/**toŋa PUA                        | taŋa PUA      | ^ t a ŋ a + PUA $       | t a ŋ a +       |
|      1 | ProtoUtoAztecan-47-knee-2        | **taŋa PUA/**toŋa PUA                        | toŋa PUA      | ^ t o ŋ a + PUA $       | t o ŋ a +       |
|      1 | ProtoUtoAztecan-48-hand-1        | *ma PUA                                      | ma PUA        | ^ m a + PUA $           | m a +           |
|      1 | ProtoUtoAztecan-49-belly-1       | **poka PUA/                                  | poka PUA      | ^ p o k a + PUA $       | p o k a +       |
|      1 | ProtoUtoAztecan-5-big-1          | *wɨL- SUA                                    | wɨL- SUA      | ^ w ɨ L - + SUA $       | w ɨ ʟ + +       |
|      1 | ProtoUtoAztecan-50-bellybutton-1 | **siku SUA                                   | siku SUA      | ^ s i k u + SUA $       | s i k u +       |
|      1 | ProtoUtoAztecan-51-neck-1        | *kusi-pa PUA                                 | kusi-pa PUA   | ^ k u s i - p a + PUA $ | k u s i + p a + |
|      1 | ProtoUtoAztecan-54-liver-1       | *nɨma PUA                                    | nɨma PUA      | ^ n ɨ m a + PUA $       | n ɨ m a +       |
|      1 | ProtoUtoAztecan-55-drink-1       | *hipi PUA                                    | hipi PUA      | ^ h i p i + PUA $       | h i p i +       |
|      1 | ProtoUtoAztecan-56-eat-1         | *kwa PUA                                     | kwa PUA       | ^ kw a + PUA $          | kʷ a +          |
|      1 | ProtoUtoAztecan-57-bite-1        | **kɨ¢a PUA                                   | kɨ¢a PUA      | ^ k ɨ ¢ a + PUA $       | k ɨ ts a +      |
|      1 | ProtoUtoAztecan-58-vomit-1       | **piso PUA/*hara SUA                         | piso PUA      | ^ p i s o + PUA $       | p i s o +       |
|      1 | ProtoUtoAztecan-58-vomit-2       | **piso PUA/*hara SUA                         | hara SUA      | ^ h a r a + SUA $       | h a r a +       |
|      1 | ProtoUtoAztecan-60-hear-1        | **kahi PUA/**nakka ’ear’ PUA                 | kahi PUA      | ^ k a h i + PUA $       | k a h i +       |
|      1 | ProtoUtoAztecan-62-sleep-1       | **ko¢i SUA                                   | ko¢i SUA      | ^ k o ¢ i + SUA $       | k o ts i +      |
|      1 | ProtoUtoAztecan-63-die-1         | **muki PUA                                   | muki PUA      | ^ m u k i + PUA $       | m u k i +       |
|      1 | ProtoUtoAztecan-67-come-1        | **yiwa SUA                                   | yiwa SUA      | ^ y i w a + SUA $       | j i w a +       |
|      1 | ProtoUtoAztecan-68-liev-1        | **wo SUA                                     | wo SUA        | ^ w o + SUA $           | w o +           |
|      1 | ProtoUtoAztecan-69-sit-1         | **yasi SUA                                   | yasi SUA      | ^ ya s i + SUA $        | j a s i +       |
|      1 | ProtoUtoAztecan-71-give-1        | *maka PUA                                    | maka PUA      | ^ m a k a + PUA $       | m a k a +       |
|      1 | ProtoUtoAztecan-72-sing-1        | **kwika PUA                                  | kwika PUA     | ^ kw i k a + PUA $      | kʷ i k a +      |
|      1 | ProtoUtoAztecan-73-sun-1         | *tawa PUA                                    | tawa PUA      | ^ tawa + PUA $          | t a w a +       |
|      1 | ProtoUtoAztecan-74-moon-1        | **mé¢a SUA                                   | mé¢a SUA      | ^ m é ¢ a + SUA $       | m e ts a +      |
|      1 | ProtoUtoAztecan-75-star-1        | **suu PUA                                    | suu PUA       | ^ s uu + PUA $          | s uː +          |
|      1 | ProtoUtoAztecan-76-sky-1         | **tawika SUA                                 | tawika SUA    | ^ t a w i k a + SUA $   | t a w i k a +   |
|      1 | ProtoUtoAztecan-77-water-1       | *pa: PUA/*wa SUA                             | pa: PUA       | ^ p a: + PUA $          | p aː +          |
|      1 | ProtoUtoAztecan-77-water-2       | *pa: PUA/*wa SUA                             | wa SUA        | ^ w a + SUA $           | w a +           |
|      1 | ProtoUtoAztecan-78-wind-1        | /**heka SUA/                                 | heka SUA      | ^ h e k a + SUA $       | h e k a +       |
|      1 | ProtoUtoAztecan-79-rainn-1       | *yuku SUA/**wi PUA                           | yuku SUA      | ^ yu k u + SUA $        | j u k u +       |
|      1 | ProtoUtoAztecan-79-rainn-2       | *yuku SUA/**wi PUA                           | wi PUA        | ^ w i + PUA $           | w i +           |
|      1 | ProtoUtoAztecan-81-stone-1       | **te SUA/**tɨ- PUA                           | te SUA        | ^ t e + SUA $           | t e +           |
|      1 | ProtoUtoAztecan-81-stone-2       | **te SUA/**tɨ- PUA                           | tɨ- PUA       | ^ t ɨ - + PUA $         | t ɨ + +         |
|      1 | ProtoUtoAztecan-83-earth-1       | **kwi PUA/**tɨpal PUA                        | kwi PUA       | ^ kw i + PUA $          | kʷ i +          |
|      1 | ProtoUtoAztecan-83-earth-2       | **kwi PUA/**tɨpal PUA                        | tɨpal PUA     | ^ t ɨ p a l + PUA $     | t ɨ p a l +     |
|      1 | ProtoUtoAztecan-84-salt-1        | **oŋa PUA/**tusa ‘white earth’ PUA           | oŋa PUA       | ^ o ŋ a + PUA $         | o ŋ a +         |
|      1 | ProtoUtoAztecan-85-cloud-2       | **tommo/**haki PUA/**musi PUA                | haki PUA      | ^ h a k i + PUA $       | h a k i +       |
|      1 | ProtoUtoAztecan-85-cloud-3       | **tommo/**haki PUA/**musi PUA                | musi PUA      | ^ m u s i + PUA $       | m u s i +       |
|      1 | ProtoUtoAztecan-87-fire-1        | **ƛahi PUA                                   | ƛahi PUA      | ^ ƛ a h i + PUA $       | tɬ a h i +      |
|      1 | ProtoUtoAztecan-9-new-1          | **hukwa SUA/**pɨtuwa PUA                     | hukwa SUA     | ^ h u kw a + SUA $      | h u kʷ a +      |
|      1 | ProtoUtoAztecan-9-new-2          | **hukwa SUA/**pɨtuwa PUA                     | pɨtuwa PUA    | ^ p ɨ t u w a + PUA $   | p ɨ t u w a +   |
|      1 | ProtoUtoAztecan-90-path-1        | **po PUA//**wo SUA                           | po PUA        | ^ p o + PUA $           | p o +           |
|      1 | ProtoUtoAztecan-90-path-2        | **po PUA//**wo SUA                           | wo SUA        | ^ w o + SUA $           | w o +           |
|      1 | ProtoUtoAztecan-91-mountain-1    | **hu-ya SUA                                  | hu-ya SUA     | ^ h u - ya + SUA $      | h u + j a +     |
|      1 | ProtoUtoAztecan-94-yellow-1      | *kosawa SUA?                                 | kosawa SUA?   | ^ k o s a w a + SUA ? $ | k o s a w a +   |
|      1 | ProtoUtoAztecan-95-white-1       | **tòsá PUA/**kwaya PUA                       | tòsá PUA      | ^ t ò s á + PUA $       | t o s a +       |
|      1 | ProtoUtoAztecan-95-white-2       | **tòsá PUA/**kwaya PUA                       | kwaya PUA     | ^ kw a ya + PUA $       | kʷ a j a +      |
|      1 | ProtoUtoAztecan-96-black-2       | **tuku/**tuL PUA                             | tuL PUA       | ^ t u L + PUA $         | t u ʟ +         |
|      1 | ProtoUtoAztecan-97-night-1       | *yuppa PUA/*tuka                             | yuppa PUA     | ^ yuppa + PUA $         | j u pp a +      |
|      1 | ProtoUtoAztecan-98-name-1        | **tɨ(n)wa PUA                                | tɨwa PUA      | ^ t ɨ w a + PUA $       | t ɨ w a +       |

**Comment by LinguList** [comment]
I fixed this, please check my profile, and the lexibank_*.py, which I used to deal with this task.

**Comment by chrzyki** [comment]
Thanks!
