### ISSUE TITLE
check concepticon concept mapping

### ISSUE THREAD

**Issue by LinguList** [lexibank/pharaocoracholaztecan#2]
Concepts are in [etc/concepts.tsv](https://github.com/lexibank/pharaocoracholaztecan/blob/master/etc/concepts.tsv). Some mappings to concepticon are missing. The file can be directly edited. A lookup, also in Spanish is [here](https://digling.org/calc/concepticon/)

**Comment by Maunus** [comment]
I think I got the last ones.
