### ISSUE TITLE
glottocodes for languages

### ISSUE THREAD

**Issue by LinguList** [lexibank/pharaocoracholaztecan#3]
They should be added, the languages are in [etc/languages.tsv](https://github.com/lexibank/pharaocoracholaztecan/blob/master/etc/languages.tsv)

**Comment by SimonGreenhill** [comment]
I'll take this -- I know these languages a bit.

**Comment by LinguList** [comment]
So only the variety for Cora is left? @Maunus, can you help here and confirm the mappings?

**Comment by Maunus** [comment]
Yes, I will take a look. Sorry, I am only half present.

**Comment by Maunus** [comment]
Done.
