### ISSUE TITLE
check the form representation of the data

### ISSUE THREAD

**Issue by LinguList** [lexibank/pharaocoracholaztecan#4]
@Maunus, you can see in [cldf/forms.csv](https://github.com/lexibank/pharaocoracholaztecan/blob/master/cldf/forms.csv) how your data is now displayed. You see that we break down multiple values per cell to just one value, which is usually the value in IPA, that we could also automatically analyze (Value is your original value, and Form is what the code made from it). If you find problems, let me know.

**Comment by Maunus** [comment]
I will look through this. It will take a little while.
SHould we add a row when there are multiple values?
For example "no" has Cora ka-mo where ka is cognate with ah- and ka, kamo is cognate with ahmo.

**Comment by LinguList** [comment]
Oh, in that case, it is better to annotate the data for partial cognates from the beginning. This can be done, when using a tool like [EDICTOR](https://digling.org/edictor/), but it would require to re-code the data. How have you handled that in your cognate sets so far?

**Comment by LinguList** [comment]
BTW: partial cognate annotation is described in a forthcoming paper [here](https://doi.org/10.17613/ab09-rj24).

**Comment by Maunus** [comment]
The way I have done it is that I have multiple forms in some of the fields. So for example when a language has two forms and one of the forms is cognate with one set of languages with cognate A and the other with the languages that have form B then they say A/B.

**Comment by LinguList** [comment]
Okay, we can handle this, but we cannot do the assignment, unless your
order follows strictly, so if you use A/B, you MUST have two forms only,
a, and b, and they should be separated by something regular. If this is
not the case, it is not problematic, we can just add the same value and
form but assign it two different times, and if you ever think of
recoding this, you could correct and only assign one value in our
long-table format, or use a partial cognate annotation schema, like the
one in EDICTOR from the beginning.

**Comment by Maunus** [comment]
I am deifnitely open to recoding it, I am interested in learning. And I think this is a set that is small enough to work on as a learning project.
