### ISSUE TITLE
convert data to nexus

### ISSUE THREAD

**Issue by LinguList** [lexibank/pharaocoracholaztecan#7]
we need an example script for @Maunus to see how the data can be converted to nexus or splitstree distances. I will place this in a folder `examples`.

**Comment by LinguList** [comment]
And when doing so, we can also convert the data to the EDICTOR wordlist, so it can be seen how alignments could be computed, etc.

**Comment by Maunus** [comment]
Yes, it would be very useful for me, if you could code the first two or three entrys, so I can see how it is done, then I can continue. I am completely new to all of this.

**Comment by LinguList** [comment]
Okay, I have added an example for conversion with this dataset to nexus and to `distances.dst` (the format that is sufficient for splitstree). The Python code is also there. I tried to do alignments, but it failed, for the orthography is not cleaned enough. But I consider this solved.

**Comment by Maunus** [comment]
I will try to clean the orthography

**Comment by Maunus** [comment]
What are the "unclean" aspects of the orthpgraphy that need to be taken care of to do alignments?

**Comment by LinguList** [comment]
- comments inside the cells (long table format allows to separate comments form pure IPA)
- non-ipa symbols
- brackets indicating unclear things (brackets don't have a real meaning in ipa)

we use a segmented form, that is: we separate all sound by a space: "m ai n", so "ai" is a dipthong, etc.. We have ways of converting our data properly. I can provide some tips here (via email is better).

**Comment by Maunus** [comment]
Ok, is it OK to change that, even though it then varies from the "official published" list?

**Comment by LinguList** [comment]
I think it is fine. People will appreciate it, I guess, and we can also derive phoneme statistics, and the like, here.

**Comment by Maunus** [comment]
What do we do with the places where a reconstruction in the PUA row is really only for SUA?

**Comment by Maunus** [comment]
I am leaning towards removing the proto-Uto-aztecan and proto-Coracho-Aztecan rows entirely, those rows were mostly meant as showing the reasoning behind the cognacy judgments.

**Comment by LinguList** [comment]
Yes, I think, if their collection is in any case not clear with semantics an the like, and you have mixed stages of a language in the same column, I'd also remove it. One could add them as examples for cognate sets. We can even do this within the code: The cognate sets ARE provided in a separate column in our standard format (not the wordlist, but what's in teh folder "cldf"): we can add one Field/Column PUA and one column for CA there, so the information is preserved, and it is also where it should be?

**Comment by Maunus** [comment]
Yes, I think this would be a good idea. The best would be to have three columns, one each for PUA, SUA and PCA. How do we delete the columns? Is there a way to do it in an automated way, or do I just delete them manually?

**Comment by LinguList** [comment]
Let us still try to avoid to manipulate the original data. It is not
difficult to adjust the code accordingly. One thing we should also keep
in mind: since this is data underlying a published study, we should not
try to optimize ad infinitum. This can be done in any follow-ups you do.
So we make a version that is reflecting ideally the counting of the
matrix you provide in the paper, plus providing the nexus. So it is
transparent, people can check it, maybe use it or improve on it, also
(mainly maybe) yourself, but everything going too much beyond this would
then be a new study.

**Comment by LinguList** [comment]
Okay, I just applied a simpler solution: SUA entries are split from the data now and listed as a separate language. Since we provide proto-forms always as a separate language, we cannot not do this here, and it makes most sense in the context to keep them. For any calculation, as shown in the examples/ folder now, one can take the subset of languages. Everything else will make it very difficult, and I think it is also time to conclude this study, as we are still only lifting a dataset that has been published, in order to illustrate how this can ideally be done beforehand. So I suggest any additional ideas calculations and the like can be done if you work on other datasets in the future and we'll glaldy help you with that. But for now, it is better to be content with what we have so far.

**Comment by Maunus** [comment]
But the SUA/PUA PCA columns were not included as data in my poriginal distane matrix, I only included them in the data file to evidence by cognacy judgments. I don't think it makes sense to have these in the distance matrix, since they are not independent of the other forms.

**Comment by LinguList** [comment]
No of course, they will be filtered, as I filtered already to show you
the distances, you see?
