### ISSUE TITLE
check everything for official release

### ISSUE THREAD

**Issue by LinguList** [lexibank/pharaocoracholaztecan#8]
The release will add this dataset on zenodo for archiving, so it is not only on github, but long-term archived. To do this, it should be checked again.

**Comment by xrotwang** [comment]
Which zenodo account would be the one "owning" the release? @Maunus or "our" institutional account?

@Maunus for some context: Zenodo ties each record to exactly one Zenodo user account - and only this user account can edit the metadata of a release. So far, there is no functionality to migrate records to different accounts or other user controled permission policies. For that reason we set up a group-owned, institutional user account, to prevent records being "locked in".

**Comment by LinguList** [comment]
For us, it would be easiest to do this with our institutional account, at least first. The title etc. is now handled pretty standard, so it would yield @maunus as author, etc., and it is probably not much more needed. And we could transfer ownership later, if @Maunus feels there are things that should be updated in the metadata?

**Comment by Maunus** [comment]
I don't mind it being tied to your institutional account. But I would like to have some more time to make sure I review the details.

**Comment by LinguList** [comment]
Yes, for sure! You should also have time to check the nexus. I do not know: do you use Python? In this case, you could also install this as a package, correct the cognate identifiers in the code, and test it yourself. In any case: if you have already now a look at the DST file (that you can paste into splitstree), to see if it is at least similar to the one you made, we have good control (you can also use the nexus file, which is binarized, so the results may slightly differ).

**Comment by LinguList** [comment]
Ah, for information: [this](https://zenodo.org/record/3746946) is an example entry from a dataset done by Aaley and Bodt. You can see that the original source is always listed, and that there are specific roles assigned to people involved. The title you see on github now is then also the title of the CLDF dataset on zenodo.

**Comment by Maunus** [comment]
I don't know python, I am pretty much a programming illiterate. 

I will check to see whether the DST file lines up with mine.

**Comment by LinguList** [comment]
Okay. I just modified the cognates according to the discussion (we can
close the issue now), and you can check how well it coincides.

**Comment by Maunus** [comment]
Excellent
